export const ORDER_CREATE_REGUEST='ORDER_CREATE_REGUEST';
export const ORDER_CREATE_SUCCESS='ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL='ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';